#pragma once

enum RenderingAPI {
	VulkanAPI
};

// Could get loaded from some Graphics.ini etc. beforehand
const static RenderingAPI RendereringAPI = RenderingAPI::VulkanAPI;

const static bool UseVsync = true;

#define PIT_CONFIGURATION_DEBUG 1
#define PIT_CONFIGURATION_DEVELOPMENT 2
#define PIT_CONFIGURATION_RELEASE 3

#define PIT_ENGINE_CONFIGURATION PIT_CONFIGURATION_DEBUG

#define PIT_ENGINE_DEBUG (PIT_ENGINE_CONFIGURATION == PIT_CONFIGURATION_DEBUG)
#define PIT_ENGINE_DEVELOPMENT (PIT_ENGINE_CONFIGURATION == PIT_CONFIGURATION_DEVELOPMENT)
#define PIT_ENGINE_RELEASE (PIT_ENGINE_CONFIGURATION == PIT_CONFIGURATION_RELEASE)